spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  redis:
    host: 127.0.0.1
    port: 6379

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 222de8a09d7ca4609f11
            client-secret: 8f8fe93178142e15900d5864128557e99cef791c
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


---
spring:
  config:
    activate:
      on-profile: prod

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 222de8a09d7ca4609f11
            client-secret: 8f8fe93178142e15900d5864128557e99cef791c

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: